---
title: "Shiny App"
output: html_document
---
```{r}
#devtools::install_github("UrbanInstitute/urbnmapr")
suppressMessages(library(shiny))
suppressMessages(library(shinythemes))
suppressMessages(library(dplyr))
suppressMessages(library(tidyverse))
suppressMessages(library(urbnmapr))
```

```{r}
load("county_data.RData")
```


```{r}
county_plot=urbnmapr::counties %>% 
    rename(State=state_abbv,County=county_name) %>% 
    mutate(County=str_replace_all(County,"County","") %>% 
           str_trim(side = "both"))
state_list = unique(county_data$State)


county_data = county_data %>% 
  rename('Housing Price' = price,
         'Income Per Capita' = Income_PerCapita,
         'Crime Rate' = crime_rate_per_100000,
         'Unemployment Rate' = pct_unemp,
         'Num Of Colleges' = college_num,
         'Num Of Public Schools' = public_school_count,
         'Num Of Private Schools' = private_school_count,
         'Hospital Rating' = hospital_rating,
         'Num Of Shoppingmalls' = num_shoppingmall,
         'Unemployment Rate' = pct_unemp,
         'Risk Level' = RiskLevel)

variable_list = c("State",
                  "County",
                  "Population",
                  "Crime Rate",
                  "Risk Level",                  
                  "Housing Price",
                  "Hospital Rating",                  
                  "Num Of Colleges",
                  "Income Per Capita",  
                  "Unemployment Rate",                    
                  "Num Of Public Schools",
                  "Num Of Private Schools",
                  "Num Of Shoppingmalls")
```

```{r}

shinyApp(
  ui = tagList(
    navbarPage(
    theme = shinytheme("cosmo"),      
    "U.S. County Housing Price",
    tabPanel("County Outlook", 
             sidebarPanel(
               selectInput("state", "Select A State", choices = state_list, selected = 1),
               checkboxGroupInput("variable","Select variables to view", variable_list),
               actionButton("update", "Update"),
               hr(),
               h3("Variable Dictionary: "),
               helpText("- Crime Rate: number of crimes per 100,000"),
               helpText("- Risk Level: 9 - Highest; 0 - lowest"),
               helpText("- Housing Price: $1000/square-meters"),
               helpText("- Hospital Rating: 5 - highest; 0 - lowest"),
               helpText("- Unemployment Rate: in percentage")
               ),
             mainPanel(
               DT::dataTableOutput("table1")
               )),
    
    tabPanel("County Housing Price",
             sidebarPanel(
               selectInput("state_hist", "Select A State", choices = state_list, selected = 1),
               sliderInput("slide", 
                           label = "Choose Your Price Range", 
                           min = 0.406, max = 4, value = c(0.5, 0.6)),
               actionButton("histogram", "Get Housing Distribution"),
               hr(),
               h3("Variable Dictionary: "),
               helpText("- Housing Price: $1000/m^2")
               ),
             mainPanel(
               plotOutput("distribution")
             )),
    
    tabPanel("Map View", 
             sidebarPanel(
               selectInput("feature", "Select A Plot Feature", 
                           choices =c("Housing Price","Income Per Capita"), selected = 1),
               actionButton("plot", "Plot"),
               hr()),
             mainPanel(
               plotOutput("plot1")
               )))
    ),
  
  server = function(input, output, session){
    
    ## panel1 
    tabledata = eventReactive(
      input$update,{
      county_data %>% filter(State == input$state) %>% select(input$variable)
    })
    
    output$table1 = DT::renderDataTable(DT::datatable({
      tabledata()
      }))
    
    ## panel 2
    plotdata = eventReactive(
      input$plot,{
      county_data  %>% select(input$feature,State,County) %>% 
              left_join(.,county_plot,by=c("State","County"))
    })
    
    output$plot1 = renderPlot({
    plotdata() %>%
    ggplot(aes(x=long, y=lat, group = group, fill = price)) +
    geom_polygon(color = NA) +
        geom_polygon(data = urbnmapr::states, mapping = aes(long, lat, group = group),
        fill = NA, color = "#ffffff") +
    coord_map(projection = "albers", lat0 = 39, lat1 = 45) +
    theme(legend.title = element_text(),
        legend.key.width = unit(.5, "in"))+
    labs(fill = "price") 

    })
    
    # panel 3
    observeEvent(
      input$state_hist, {
        histdata = county_data %>% filter(State == input$state_hist)
        updateSliderInput(session, "slide",
                          min = min(histdata$`Housing Price`),
                          max = max(histdata$`Housing Price`))
      })
    
    histdata = eventReactive(
      input$histogram, {
        county_data %>% filter(State == input$state_hist,
                               `Housing Price`<= input$slide[2],
                               `Housing Price` >= input$slide[1])
      }
    )
    
    output$distribution = renderPlot({
      plot = histdata()
      
      ggplot(data = plot, 
             aes(x = reorder(County, -`Housing Price`), 
                 y = `Housing Price`,
                 fill = `Housing Price`)) +
        geom_bar(stat = "identity",
                 color = "black",
                 position = position_dodge()) +
        geom_text(aes(label = `Housing Price`),
                  position = position_dodge(0.9),
                  vjust = 1.6,
                  size = 3.5,
                  color = "black") +
        xlab("County") +
        ylab("Housing Price ($1000/m^2)") +
        theme(axis.text.x = element_text(angle = 40, hjust = 1, vjust = 1)) +
        scale_fill_gradient(low="lightblue", high="pink")
      })
  }
  
)

```



