---
title: "sta523 final project"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

```{r}
library(Quandl)
library(readr)
library(dplyr)
library(rvest)
library(stringr)
library(xlsx)
library(noncensus)
library(rvest)
library(tidyverse)
library(sqldf)
library(stringi)
library(readxl)
library(tools)
```

## 1. base data

```{r}
pricepersqft = read_csv("pricepersqft__.csv")

county_count = pricepersqft %>% dplyr::select(County,State) %>% 
  group_by(County,State) %>% summarize(count = length(County))

price_2017 = pricepersqft %>% 
  dplyr::select(County,State, `17-Jan`) %>%
  group_by(County,State) %>% 
  summarize(price = median(`17-Jan`))
```


## 2. Population data from wikipedia

```{r}
url <- "https://en.wikipedia.org/wiki/List_of_United_States_counties_by_per_capita_income"

df = read_html(url) %>%
  html_nodes("table.wikitable.sortable") %>%
  .[[1]] %>%
  html_table() %>% 
  filter(.$State != "")


county_data <- data.frame(
  County = df$`County-equivalent` %>% as.character(.),
  State = df$State %>% as.character(.),
  Income_PerCapita = df$`Per capitaincome` %>% 
    str_replace_all(",", "") %>%
    substr(2, 10000) %>% 
    as.numeric(as.character(.)),
  Median_Household_Income = df$Medianhouseholdincome %>% 
    str_replace_all(",", "") %>%
    substr(2, 10000) %>% 
    as.numeric(as.character(.)),
  Median_Family_Income = df$Medianfamilyincome %>% 
    str_replace_all(",", "") %>%
    substr(2, 10000) %>% 
    as.numeric(as.character(.)),
  Population = df$Population %>% 
    str_replace_all(",", "") %>% 
    as.numeric(as.character(.)),
  Num_Household = df$`Number ofhouseholds` %>% 
    str_replace_all(",", "") %>% 
    as.numeric(as.character(.))
)

county_data$State = state.abb[match(county_data$State,state.name)]

'%ni%' <- Negate('%in%')

difficult_county = price_2017[price_2017$County %ni% county_data$County,]
```

```{r}
w = which(price_2017$County == difficult_county$County[1])
w[length(w)]
price_2017[w[1]:w[length(w)], 1] = 'Delaware County'

w = which(price_2017$County == difficult_county$County[8])
ww = which(price_2017$County == difficult_county$County[25])

price_2017[w[1]:ww, 1] = w[1]:ww %>% sapply(function(i){
     paste0('St.',substr(price_2017[i,1],6,100))})

w = which(price_2017$County == difficult_county$County[26])
price_2017[w[1]:w[length(w)], 1] = 'Washington County'

difficult_county = price_2017[price_2017$County %ni% county_data$County,]

w = which(price_2017$County == difficult_county$County[3])
price_2017[w[1]:w[length(w)], 1] = 'St. Louis County'

w = which(price_2017$County == difficult_county$County[5])
price_2017[w[1]:w[length(w)], 1] = "St. Mary's"

price_2017_2 = merge(price_2017,county_data,by = c('County','State'))

```

## 3. hilton data within the country

```{r}
baseURL =  "https://www3.hilton.com"
links = read_html("https://www3.hilton.com/en/hotel-locations/us/index.html") %>%
    html_nodes(.,'ul.directory_locations_list li a') 
states = html_text(links)
urls = html_attr(links, "href") %>% paste0(baseURL, .)

zips = sapply(urls, function(url){
     url %>%
         read_html() %>%
         html_nodes('ul.directory_locations_list li a') %>%
         {paste0(baseURL, html_attr(., "href"))} %>%
         sapply(function(locationURL){
             locationURL %>%
                 read_html() %>%
                 html_nodes('ul.directory_hotels_list li') %>%
                 html_text() %>%
                 str_replace("\t", "") %>%
                 str_replace("\r\n", "") %>%
                 {strsplit(., " ")[[1]]} %>%
                 {.[length(.)]} %>%
                 {strsplit(., "USA")[[1]][1]} %>%
                 substr(1, 5)
             })
 }) %>%
     unlist() %>%
     unname() %>%
    as.data.frame() 
colnames(zips) = "zips"
```

```{r}
zip_county_lookup = read_csv("ZIP-COUNTY-FIPS_2018-03.csv") %>%
    mutate(County = COUNTYNAME)

hilton_county = merge(zips,zip_county_lookup,by.x ='zips',by.y = 'ZIP') %>%
     mutate(COUNTYNAME = COUNTYNAME %>%
                str_locate_all(" ") %>%
                sapply(function(mat){mat[min(dim(mat), 2), 1] - 1}) %>%
                {str_sub(COUNTYNAME, 1, .)})

distinct_count = hilton_county%>%
  group_by(COUNTYNAME,STATE) %>%
  summarize(count = length(COUNTYNAME)) %>%
    mutate(hilton_count = count) %>% 
    dplyr::select(COUNTYNAME,STATE,hilton_count)
    
price_2017_3 = left_join(price_2017_2, distinct_count, by = c("County"="COUNTYNAME","State" = "STATE")) %>%
  mutate_all(funs(replace(., is.na(.), 0)))

```


## 4. clean the dataset 

```{r}
clean_county = function(df){
df$County = strsplit(df$County, " ")
 n = dim(df)[1]
for (i in 1:n){
  if (length(df$County[[i]])>1){
    if (df$County[[i]][length(df$County[[i]])] == 'County' 
    | df$County[[i]][length(df$County[[i]])] == 'Borough'  
    |df$County[[i]][length(df$County[[i]])] == 'Parish'
    |df$County[[i]][length(df$County[[i]])] ==
    'Municipality'
    |df$County[[i]][length(df$County[[i]])] == 'Municipio'
    |df$County[[i]][length(df$County[[i]])] == 'Island'
    |df$County[[i]][length(df$County[[i]])] == 'County,' 
    |df$County[[i]][length(df$County[[i]])] == 'Borough,'  
    |df$County[[i]][length(df$County[[i]])] == 'Parish,'
    |df$County[[i]][length(df$County[[i]])] ==
    'Municipality,'
    |df$County[[i]][length(df$County[[i]])] == 'Municipio,'
    |df$County[[i]][length(df$County[[i]])] == 'Island,')
    {df$County[[i]] = df$County[[i]][-length(df$County[[i]])]}
      
    if (df$County[[i]][length(df$County[[i]])] == 'city' 
    | df$County[[i]][length(df$County[[i]])] == 'City'
    | df$County[[i]][length(df$County[[i]])] == 'city,' 
    | df$County[[i]][length(df$County[[i]])] == 'City,')
    {df$County[[i]][length(df$County[[i]])] = 'City'}}
}
for (i in 1:n){
  if (length(df$County[[i]]) == 2){
    df$County[[i]] = paste(df$County[[i]][1],df$County[[i]][2])}
  if (length(df$County[[i]]) == 3) {
    df$County[[i]] = paste(df$County[[i]][1],df$County[[i]][2],df$County[[i]][3])}
  if (length(df$County[[i]]) == 4) {
    df$County[[i]] = paste(df$County[[i]][1],df$County[[i]][2],df$County[[i]][3],df$County[[i]][4])}
  if (length(df$County[[i]]) == 5) {
    df$County[[i]] = paste(df$County[[i]][1],df$County[[i]][2],df$County[[i]][3],df$County[[i]][4],df$County[[i]][5])}
}
 df$County = unlist(df$County)
 return(df)
}

bind = function(df){
  for (i in 1:n){
  if (length(df$County[[i]]) == 2){
    df$County[[i]] = paste(df$County[[i]][1],df$County[[i]][2])}
  if (length(df$County[[i]]) == 3) {
    df$County[[i]] = paste(df$County[[i]][1],df$County[[i]][2],df$County[[i]][3])}
  if (length(df$County[[i]]) == 4) {
    df$County[[i]] = paste(df$County[[i]][1],df$County[[i]][2],df$County[[i]][3],df$County[[i]][4])}
  if (length(df$County[[i]]) == 5) {
    df$County[[i]] = paste(df$County[[i]][1],df$County[[i]][2],df$County[[i]][3],df$County[[i]][4],df$County[[i]][5])}
}
 df$County = unlist(df$County)
 return(df)
}
```

```{r}
price_2017_4 = clean_county(price_2017_3) 
zip_county_lookup = clean_county(zip_county_lookup) %>%
  dplyr::select(ZIP,STATE,County,CITY)
```


## 5. crime rate data

```{r}
crime_data = read_csv("crime_data_w_population_and_crime_rate.csv")
crime_data = crime_data %>%
  select(county_name,crime_rate_per_100000,IDNO,CPOPCRIM,CPOPARST,COVIND,MURDER,RAPE,ROBBERY,AGASSLT,BURGLRY,LARCENY,MVTHEFT,ARSON)

crime_data$county_name = strsplit(crime_data$county_name, " ") 
crime_data$State = NA
colnames(crime_data)[1] = "County"
for (i in 1:dim(crime_data)[1]){
  crime_data$State[i] = crime_data$County[[i]][length(crime_data$County[[i]])]
  crime_data$County[[i]] = crime_data$County[[i]][-length(crime_data$County[[i]])]}

crime_data = crime_data %>% bind() %>% clean_county()
price_2017_5 = merge(price_2017_4,crime_data,by=c('County','State'))

crime_lost = price_2017_4[price_2017_4$County %ni% price_2017_5$County,]
w = which(crime_data$County == 'Larue')
crime_data$County[w] = crime_lost$County[1]
price_2017_5 = left_join(price_2017_4,crime_data,by=c('County','State'))
```

## 6. tax rate data

```{r}
setwd("TAXRATES_ZIP5")
filenames = list.files(pattern = "*.csv")
tax_rate_data = read.csv(filenames[1])
for(i in 2:length(filenames)){
  temp = read.csv(filenames[i])
  tax_rate_data = rbind(tax_rate_data, temp)
}
tax_rate_data = left_join(tax_rate_data,zip_county_lookup,by=c("ZipCode"="ZIP"))

tax_rate_data = tax_rate_data %>% select(County,State,StateRate,EstimatedCombinedRate,EstimatedCountyRate,EstimatedCityRate,EstimatedSpecialRate,RiskLevel)

tax_rate_data = tax_rate_data[!duplicated(tax_rate_data[,1:2]), ]
Price_2017_6 = left_join(price_2017_5,tax_rate_data,by=c('County','State'))
```

## 7. gasoline price data

```{r}
get_gasoline = function(k){
    dat = trimws(html_text(html_nodes(web, paste0("td:nth-child(",k,")"))))
}

web = read_html("https://gasprices.aaa.com/state-gas-price-averages/")
gasoline_data = data.frame(State=get_gasoline(1), Regular=get_gasoline(2), MidGrade=get_gasoline(3), Premium=get_gasoline(4), Diesel=get_gasoline(5))

gasoline_data$State = state.abb[match(gasoline_data$State,state.name)]
price_2017_7 = left_join(Price_2017_6,gasoline_data,by='State')

```

## 8. number of colleges

```{r}
## reference: https://nces.ed.gov/ipeds/datacenter/InstitutionProfile.aspx

schools = read_html("IPEDS Data Center.html") %>%
    html_node("table.idc_gridview") %>%
    html_table() %>%
    select(-X1) %>% .[-1,]

colnames(schools) = c("school", "City", "State")

cities = zip_county_lookup %>% select(CITY, County, STATE) %>% unique() %>%
    rename(State = STATE, City = CITY)

school_data = left_join(schools,cities, by=c('City','State'))%>% 
    group_by(County, State) %>%
    summarise(college_num = n()) 

price_2017_8 = left_join(price_2017_7, data, by=c('County','State')) %>%
    mutate(college_num = ifelse(is.na(college_num), 0, college_num))
```

## 9. Traffic data 

```{r}
epidata = read_csv("EQIDATA_ALL_DOMAINS_2014MARCH11.CSV") %>% 
  select(county_name,state,hwyprop,ryprop,
         pct_pub_transport_log,fatal_rate_log,
         pct_pers_lt_pov,pct_unemp) %>% 
  rename(County=county_name,State=state)%>% 
  mutate(County=str_replace_all(County,"County","") %>% 
           str_trim(side = "both"))

price_2017_9 =left_join(price_2017_8, epidata,by=c('County','State'))%>%
  mutate_all(funs(replace(., is.na(.), 0)))

```

## 10. shopping mall data 

```{r}
read_wikitable_flat = function(state,n1,k,n4,n5,l4,l5){
    l1 = n1+1
    url = paste0("https://en.wikipedia.org/wiki/List_of_shopping_malls_in_",state)
    dat = read_html(url) %>%
  html_nodes("table.wikitable.sortable") %>%
  html_table() %>% flatten()
  data=data.frame(
  name=c(dat[[1]] %>% as.character(.),dat[[n1]] %>% as.character(.),
         dat[[n1+k]] %>% as.character(.),dat[[n1+2*k]] %>% as.character(.),
         dat[[n4]] %>% as.character(.),dat[[n5]] %>% as.character(.)
  ),
  location=c(dat[[2]] %>% as.character(.),dat[[l1]] %>% as.character(.),
             dat[[l1+k]] %>% as.character(.),dat[[l1+2*k]] %>% as.character(.),
             dat[[l4]] %>% as.character(.),dat[[l5]] %>% as.character(.)
  ))
  return(data)
}

read_wikitable_nonflat = function(state){
  url = paste0("https://en.wikipedia.org/wiki/List_of_shopping_malls_in_",state)
  dat = read_html(url) %>%
  html_nodes("table.wikitable.sortable") %>%
  html_table() 
  data = data_frame(
  name = dat[[1]][[1]] %>% as.character(.),
  location=dat[[1]][[2]] %>% as.character(.)
)
  return(data)
}

read_wikilist = function(state,n){
url = paste0("https://en.wikipedia.org/wiki/List_of_shopping_malls_in_",state)
page = read_html(url)
dat = data_frame(
  name=html_nodes(page,"li") %>% html_text() 
) %>% .[1:n,] %>%
  separate(name, c("name", "location"), "-",remove=TRUE)
}

read_texas = function(p){
 url = "https://en.wikipedia.org/wiki/List_of_shopping_malls_in_Texas"
 dat = read_html(url) %>%
  html_nodes("table.wikitable.sortable") %>%
  .[[p]] %>% 
  html_table(fill=TRUE) 
dat = dat[,1:2]
colnames(dat)<-c("name","location")
return(dat)
}

page = read_html("https://en.wikipedia.org/wiki/List_of_shopping_malls_in_the_United_States")

st_data = data_frame(
  name=html_nodes(page,"li") %>% html_text() 
) %>% .[59:879,] %>% 
  separate(name, c("name", "location1"), " . ",remove=TRUE)%>%
  separate(name, c("name", "location2"), "–",remove=TRUE, extra = "merge") %>% 
  mutate(location = coalesce(location1,location2)) %>%
  select(name, location)

shooping_mall_num = read_xlsx("shooping_mall_num.xlsx",1)
shopping = shooping_mall_num[rep(row.names(shooping_mall_num), shooping_mall_num$'Number of Malls'), 1] %>%
  as.data.frame() %>% .[1:821,]
st_data = st_data %>% mutate(STATE = shopping)

shopping_mall_data = bind_rows(
    al_data = read_wikitable_nonflat("Alabama") %>% mutate('STATE' = 'AL'),
    ca_data = read_wikilist("California",181) %>%
  separate(location, c("location", "state"), ",",remove=TRUE, extra = "merge") %>% 
  select(name, location) %>% 
  mutate('STATE' = 'CA'),
  md_data = read_wikilist("Maryland",34) %>% mutate('STATE' = 'MD'),
  mi_data = read_wikitable_flat("Michigan",8,7,29,36,30,37) %>% 
    separate(location, c("location", "latitude"), "4",remove=TRUE, extra = "merge") %>% select(name, location) %>% 
  mutate('STATE' = 'MI'),
  nj_data = read_wikitable_nonflat("New_Jersey") %>% mutate('STATE' = 'NJ'),
  or_data = read_wikitable_flat("Oregon",7,5,NA,NA,NA,NA) %>% 
  mutate('STATE' = 'OR'),
  pa_data = read_wikitable_nonflat("Pennsylvania") %>% mutate('STATE' = 'PA'),
  tx_data = rbind(read_texas(1),read_texas(2),read_texas(3),
                texas = read_wikilist("Texas",50) %>% .[15:50,] %>% separate(location, c("location", "other"), "[(]",remove=TRUE, extra = "merge") %>% 
  select(name, location)) %>% 
  mutate('STATE' = 'TX'),
  st_data)

shopping_mall_data_clean = shopping_mall_data %>%
  select(name, location)%>%
  separate(name, c("name", "other"), "[(]",remove=TRUE)%>%
  select(name, location)%>%
  separate(location, c("location", "other"), "[(]",remove=TRUE) %>%
  select(name, location)

shopping_mall_data = bind_cols(shopping_mall_data_clean,shopping_mall_data) %>% 
    select(name,location,STATE) %>% 
    rename(City = location, State = STATE)
```

```{r}
shopping_mall_data$City = tolower(shopping_mall_data$City) %>% str_trim(.,"left")
cities$City = tolower(cities$City)

shopping_mall_data_final = merge(shopping_mall_data,cities,by=c("City","State")) %>%
  select(name,City,State,County) %>% unique() %>%
  group_by(County,State) %>%
  summarise(num_shoppingmall = length(County)) 

price_2017_10 = left_join(price_2017_9,shopping_mall_data_final,by=c("County","State")) %>% 
    mutate(num_shoppingmall = ifelse(is.na(num_shoppingmall), 0, num_shoppingmall))
```


## 11. Public high school data

```{r}
public_school = read.csv("Public_high_school.csv", stringsAsFactors=FALSE) %>% 
    select(1, 2, 4) %>%
    rename(State = County.Name, County = County.Name..Public.School..2015.16, public_school_num = Total.Number.of.Public.Schools..Public.School..2015.16) %>%
    mutate(County = str_trim(str_replace(.$County, "County", "")),
           public_school_num = as.numeric(public_school_num),
           State = stri_sub(str_trim(State), -2, -1)) %>% 
    na.omit() %>%
    group_by(County, State) %>% 
    summarise(public_school_count = sum(public_school_num, na.rm = TRUE))

price_2017_11 = left_join(price_2017_10, public_school, by=c('County','State')) %>%
    mutate(public_school_count = ifelse(is.na(public_school_count), 0, public_school_count))
```

## 12. Private high school data

```{r}
private_school = read.csv("Private_high_school.csv", stringsAsFactors=FALSE) %>% 
    select(2, 5) %>% 
    rename(State = State.Name..Private.School..Latest.available.year, County = County.Name..Private.School..2015.16) %>% 
    mutate(State = state.abb[match(toTitleCase(tolower(State)),state.name)],
           County = toTitleCase(tolower(County))) %>%
    group_by(County, State) %>% 
    summarise(private_school_count = n()) 

price_2017_12 = left_join(price_2017_11, private_school, by=c('County','State')) %>%
    mutate(private_school_count = ifelse(is.na(private_school_count), 0, private_school_count))
```


## 13. Hospital data

```{r}
hospital = private_school = read.csv("HospInfo.csv", stringsAsFactors=FALSE) %>%
    select(Hospital.Name, County.Name, State,Emergency.Services, Hospital.overall.rating ) %>% rename(Name = Hospital.Name, County = County.Name, Emergency= Emergency.Services, rating = Hospital.overall.rating) %>%
    mutate(County = toTitleCase(tolower(County)),
           Emergency = as.numeric(Emergency),
           rating = as.numeric(rating)) %>%
    group_by(County, State) %>%
    summarise(num_hospitals = length(County),
              num_emergency = sum(Emergency),
              hospital_rating = mean(rating,na.rm = TRUE)) %>%
    mutate(hospital_rating = ifelse(is.nan(hospital_rating), 0, hospital_rating))

price_2017_13 = left_join(price_2017_12, hospital2, by=c('County','State')) %>%
    mutate(num_hospitals = ifelse(is.na(num_hospitals), 0, num_hospitals),
           num_emergency = ifelse(is.na(num_emergency), 0, num_emergency),
           hospital_rating = ifelse(is.na(hospital_rating), 0, hospital_rating))
```




